trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: docker-creds
  - group: image-cred

stages:
  - stage: DockerLogin
    displayName: Docker Login
    jobs:
      - job: DockerLogin
        steps: 
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Docker Login'